### ISSUE TITLE
Results-branchname?

### ISSUE THREAD

**Issue by strowi** [rcarmstrong/go-bamboo#9]
Hi,

i'm trying to build a bamboo-exporter for our projects. Stumbling over this nice project, i tried using sth like

`
			pipelines, _, err := client.Plans.ListPlanKeys()
			if err != nil {
				log.Fatalln(err)
			}

			for _, plan := range pipelines {
				result, _, _ := client.Results.LatestResult(plan)
`
But it seems there is no BranchName in the result. Looking through the REST-API it seems it is available under /results.
Would it be possible to add this? Using VcsRevisionKey is not really useable..

regards,
Roman

**Comment by strowi** [comment]
sorry, forget it. Found the solution.. still new to go.

**Comment by rcarmstrong** [comment]
No problem, glad you found the solution. Thanks for taking an interest in this project 👍
